version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pp_be_app
    container_name: pp_be_app_container
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - pp_network

  db:
    image: postgres:16.1
    container_name: pp_be_postgress
    restart: unless-stopped
    environment:
      POSTGRES_USER: pp_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pp_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - pp_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - pp_network

  redis:
    image: redis:7.2.3
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pp_network

  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - pp_network

volumes:
  postgres-data:
  elasticsearch-data:

networks:
  pp_network:
